module.exports = {
  SUPER: 'SUPER',
  ADMIN_VIEW: 'ADMIN_VIEW',
  ADMIN_PUBLISH: 'ADMIN_PUBLISH',
  EMPLOYEE_VIEW: 'EMPLOYEE_VIEW',
  EMPLOYEE_PUBLISH: 'EMPLOYEE_PUBLISH',
  CATALOGUE_VIEW: 'VIEW_CATALOGUE',
  CATALOGUE_PUBLISH: 'PUBLISH_CATALOGUE'
}
