module.exports = {
  SUPER: 'SUPER',
  ADMIN_VIEW: 'ADMIN_VIEW',
  ADMIN_PUBLISH: 'ADMIN_PUBLISH',
  EMPLOYEE_VIEW: 'EMPLOYEE_VIEW',
  EMPLOYEE_PUBLISH: 'EMPLOYEE_PUBLISH',
  VIEW_CATALOGUE: 'VIEW_CATALOGUE',
  PUBLISH_CATALOGUE: 'PUBLISH_CATALOGUE'
}
