export const SUPER = 'SUPER';
export const ADMIN_VIEW = 'ADMIN_VIEW';
export const ADMIN_PUBLISH = 'ADMIN_PUBLISH';
export const EMPLOYEE_VIEW = 'EMPLOYEE_VIEW';
export const EMPLOYEE_PUBLISH = 'EMPLOYEE_PUBLISH';
export const VIEW_CATALOGUE = 'VIEW_CATALOGUE';
export const PUBLISH_CATALOGUE = 'PUBLISH_CATALOGUE';
